### ISSUE TITLE
Unable to delete custom attributes

### ISSUE THREAD

**Issue by tardinha** [nglasl/silverstripe-mediawesome#11]
Custom attributes aren't able to be deleted from a media type. They can be renamed though,

**Comment by nglasl** [comment]
That is correct, once a media attribute has been created, it is unable to be deleted. This was a design decision, because it's possible that a media page has started using that media attribute. This shouldn't cause any issues though, as you don't **need** to use the media attribute (it only really causes clutter). I do agree though, this is probably something that could be improved further down the track (I would be leaning towards completely re-working the media attributes for this).
